nl:
  languageName: Nederlands
  contentDir: content/nl
  weight: 1
  disabled: false
  params:
    flag:
  permalinks:
    page:
      posts: /blog/:slug
      services: /diensten/:slug
    section:
      posts: /blog/
      services: /diensten/