# -- Site specifieke params
author: "Q en A Verzuimadvies"
description: "Q en A Verzuimadvies biedt professionele verzuimbegeleiding, re-integratieadvies en verzuimpreventie voor bedrijven. Persoonlijk en doelgericht advies door Annemiek"
keywords:
  - verzuimbegeleiding
  - re-integratieadvies
  - verzuimpreventie
  - verzuimadvies
  - verzuimbeleid
  - verzuimcoach
  - mkb verzuim
  - Q en A Verzuimadvies
  - Annemiek
favicon: "/images/favicon.ico"
logo: "/uploads/logo.png"


# -- SEO params --
seo:
  enable: true
  twitter_card: "summary_large_image"
  og_image: "/images/og-image.png"

# -- Schema --
schema:
  type: "Organization"
  name: "Q en A Verzuimadvies"
  url: "https://qenaverzuimadvies.nl"
  logo: "/uploads/logo.png"
  sameAs:
    - "https://www.linkedin.com/company/voorbeeldbedrijf"
    - "https://twitter.com/voorbeeldbedrijf"

# -- Socials --
social:
  - name: "twitter"
    url: "https://twitter.com/jouwaccount"
  - name: "facebook"
    url: "https://facebook.com/jouwaccount"